name: CheckLinks

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  checklinks:
    name: Check website links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Move site into place
        run: |
          sudo mv ./build/* ./_site
          rm -rf ./_site/src

      - name: Check for broken links
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          # The directory to scan
          arguments: --check_external_hash --assume_extension --only_4xx --ignore_status_codes 429,403 --allow_missing_href --allow_hash_href --checks 'Links' --ignore_urls "https://onnxruntime.ai/docs/reference/api/c-api.html,https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#c-api-example,https://www.onnxruntime.ai/docs/resources/graph-optimizations.html,onnxruntime/capi/onnxruntime_pybind11_state.html,https://github.com/microsoft/onnx-converters-private/issues/new/choose,https://aka.ms/onnx/exportissue,https://aka.ms/onnx/board" --log-level :info 
          # The arguments to pass to HTMLProofer